# Archivo de configuración de la aplicación

spring.application.name=videocall
server.port=5050

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=@Ruben2005
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot